coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: backend
      paths:
        - /
      statuses:
        - type: project
          target: auto
          threshold: 1%