apiVersion: v1
kind: Namespace
metadata:
  name: printqueue
---
apiVersion: v1
kind: Service
metadata:
  name: printqueue
  namespace: printqueue
  labels:
    app: printqueue
spec:
  type: NodePort
  metadata:
    labels:
      app: printqueue
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: printqueue
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: printqueue
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - printqueue
  selector:
    matchLabels:
      app: printqueue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: printqueue
  namespace: printqueue
spec:
  selector:
    matchLabels:
      app: printqueue
  replicas: 3
  template:
    metadata:
      labels:
        app: printqueue
    spec:
      containers:
      - name: printqueue
        image: registry.brotherlogic-backend.com/brotherlogic/printqueue:0.40.0 # {"$imagepolicy": "flux-system:printqueue"}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
