// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: printqueue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Destination int32

const (
	Destination_DESTINATION_UNKNOWN Destination = 0
	Destination_DESTINATION_RECEIPT Destination = 1
)

// Enum value maps for Destination.
var (
	Destination_name = map[int32]string{
		0: "DESTINATION_UNKNOWN",
		1: "DESTINATION_RECEIPT",
	}
	Destination_value = map[string]int32{
		"DESTINATION_UNKNOWN": 0,
		"DESTINATION_RECEIPT": 1,
	}
)

func (x Destination) Enum() *Destination {
	p := new(Destination)
	*p = x
	return p
}

func (x Destination) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Destination) Descriptor() protoreflect.EnumDescriptor {
	return file_printqueue_proto_enumTypes[0].Descriptor()
}

func (Destination) Type() protoreflect.EnumType {
	return &file_printqueue_proto_enumTypes[0]
}

func (x Destination) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Destination.Descriptor instead.
func (Destination) EnumDescriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{0}
}

type PrintRequest_Urgency int32

const (
	PrintRequest_URGENCY_UNKNOWN   PrintRequest_Urgency = 0
	PrintRequest_URGENCY_REGULAR   PrintRequest_Urgency = 1
	PrintRequest_URGENCY_IMMEDIATE PrintRequest_Urgency = 2
)

// Enum value maps for PrintRequest_Urgency.
var (
	PrintRequest_Urgency_name = map[int32]string{
		0: "URGENCY_UNKNOWN",
		1: "URGENCY_REGULAR",
		2: "URGENCY_IMMEDIATE",
	}
	PrintRequest_Urgency_value = map[string]int32{
		"URGENCY_UNKNOWN":   0,
		"URGENCY_REGULAR":   1,
		"URGENCY_IMMEDIATE": 2,
	}
)

func (x PrintRequest_Urgency) Enum() *PrintRequest_Urgency {
	p := new(PrintRequest_Urgency)
	*p = x
	return p
}

func (x PrintRequest_Urgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrintRequest_Urgency) Descriptor() protoreflect.EnumDescriptor {
	return file_printqueue_proto_enumTypes[1].Descriptor()
}

func (PrintRequest_Urgency) Type() protoreflect.EnumType {
	return &file_printqueue_proto_enumTypes[1]
}

func (x PrintRequest_Urgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrintRequest_Urgency.Descriptor instead.
func (PrintRequest_Urgency) EnumDescriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{0, 0}
}

type PrintRequest_FANOUT int32

const (
	PrintRequest_FANOUT_UNKNOWN PrintRequest_FANOUT = 0
	PrintRequest_FANOUT_ONE     PrintRequest_FANOUT = 1
	PrintRequest_FANOUT_ALL     PrintRequest_FANOUT = 2
)

// Enum value maps for PrintRequest_FANOUT.
var (
	PrintRequest_FANOUT_name = map[int32]string{
		0: "FANOUT_UNKNOWN",
		1: "FANOUT_ONE",
		2: "FANOUT_ALL",
	}
	PrintRequest_FANOUT_value = map[string]int32{
		"FANOUT_UNKNOWN": 0,
		"FANOUT_ONE":     1,
		"FANOUT_ALL":     2,
	}
)

func (x PrintRequest_FANOUT) Enum() *PrintRequest_FANOUT {
	p := new(PrintRequest_FANOUT)
	*p = x
	return p
}

func (x PrintRequest_FANOUT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrintRequest_FANOUT) Descriptor() protoreflect.EnumDescriptor {
	return file_printqueue_proto_enumTypes[2].Descriptor()
}

func (PrintRequest_FANOUT) Type() protoreflect.EnumType {
	return &file_printqueue_proto_enumTypes[2]
}

func (x PrintRequest_FANOUT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrintRequest_FANOUT.Descriptor instead.
func (PrintRequest_FANOUT) EnumDescriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{0, 1}
}

type PrintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines       []string             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Origin      string               `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Urgency     PrintRequest_Urgency `protobuf:"varint,3,opt,name=urgency,proto3,enum=printqueue.PrintRequest_Urgency" json:"urgency,omitempty"`
	Destination Destination          `protobuf:"varint,4,opt,name=destination,proto3,enum=printqueue.Destination" json:"destination,omitempty"`
}

func (x *PrintRequest) Reset() {
	*x = PrintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printqueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintRequest) ProtoMessage() {}

func (x *PrintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_printqueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintRequest.ProtoReflect.Descriptor instead.
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{0}
}

func (x *PrintRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *PrintRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PrintRequest) GetUrgency() PrintRequest_Urgency {
	if x != nil {
		return x.Urgency
	}
	return PrintRequest_URGENCY_UNKNOWN
}

func (x *PrintRequest) GetDestination() Destination {
	if x != nil {
		return x.Destination
	}
	return Destination_DESTINATION_UNKNOWN
}

type PrintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PrintResponse) Reset() {
	*x = PrintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printqueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResponse) ProtoMessage() {}

func (x *PrintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_printqueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResponse.ProtoReflect.Descriptor instead.
func (*PrintResponse) Descriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{1}
}

func (x *PrintResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClientPrintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines       []string    `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Origin      string      `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination Destination `protobuf:"varint,3,opt,name=destination,proto3,enum=printqueue.Destination" json:"destination,omitempty"`
}

func (x *ClientPrintRequest) Reset() {
	*x = ClientPrintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printqueue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPrintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPrintRequest) ProtoMessage() {}

func (x *ClientPrintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_printqueue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPrintRequest.ProtoReflect.Descriptor instead.
func (*ClientPrintRequest) Descriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{2}
}

func (x *ClientPrintRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *ClientPrintRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ClientPrintRequest) GetDestination() Destination {
	if x != nil {
		return x.Destination
	}
	return Destination_DESTINATION_UNKNOWN
}

type ClientPrintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientPrintResponse) Reset() {
	*x = ClientPrintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_printqueue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPrintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPrintResponse) ProtoMessage() {}

func (x *ClientPrintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_printqueue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPrintResponse.ProtoReflect.Descriptor instead.
func (*ClientPrintResponse) Descriptor() ([]byte, []int) {
	return file_printqueue_proto_rawDescGZIP(), []int{3}
}

var File_printqueue_proto protoreflect.FileDescriptor

var file_printqueue_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0xbd,
	0x02, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a,
	0x07, 0x75, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20,
	0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x52, 0x07, 0x75, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x39, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x07, 0x55, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59, 0x5f,
	0x52, 0x45, 0x47, 0x55, 0x4c, 0x41, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x52, 0x47,
	0x45, 0x4e, 0x43, 0x59, 0x5f, 0x49, 0x4d, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x54, 0x45, 0x10, 0x02,
	0x22, 0x3c, 0x0a, 0x06, 0x46, 0x41, 0x4e, 0x4f, 0x55, 0x54, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x41,
	0x4e, 0x4f, 0x55, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x46, 0x41, 0x4e, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x46, 0x41, 0x4e, 0x4f, 0x55, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x22, 0x1f,
	0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x7d, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x39, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15,
	0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x3f, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x53, 0x54, 0x49, 0x4e, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a,
	0x13, 0x44, 0x45, 0x53, 0x54, 0x49, 0x4e, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x43,
	0x45, 0x49, 0x50, 0x54, 0x10, 0x01, 0x32, 0x4e, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x66, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_printqueue_proto_rawDescOnce sync.Once
	file_printqueue_proto_rawDescData = file_printqueue_proto_rawDesc
)

func file_printqueue_proto_rawDescGZIP() []byte {
	file_printqueue_proto_rawDescOnce.Do(func() {
		file_printqueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_printqueue_proto_rawDescData)
	})
	return file_printqueue_proto_rawDescData
}

var file_printqueue_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_printqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_printqueue_proto_goTypes = []interface{}{
	(Destination)(0),            // 0: printqueue.Destination
	(PrintRequest_Urgency)(0),   // 1: printqueue.PrintRequest.Urgency
	(PrintRequest_FANOUT)(0),    // 2: printqueue.PrintRequest.FANOUT
	(*PrintRequest)(nil),        // 3: printqueue.PrintRequest
	(*PrintResponse)(nil),       // 4: printqueue.PrintResponse
	(*ClientPrintRequest)(nil),  // 5: printqueue.ClientPrintRequest
	(*ClientPrintResponse)(nil), // 6: printqueue.ClientPrintResponse
}
var file_printqueue_proto_depIdxs = []int32{
	1, // 0: printqueue.PrintRequest.urgency:type_name -> printqueue.PrintRequest.Urgency
	0, // 1: printqueue.PrintRequest.destination:type_name -> printqueue.Destination
	0, // 2: printqueue.ClientPrintRequest.destination:type_name -> printqueue.Destination
	3, // 3: printqueue.PrintService.Print:input_type -> printqueue.PrintRequest
	5, // 4: printqueue.PrintClientService.ClientPrint:input_type -> printqueue.ClientPrintRequest
	4, // 5: printqueue.PrintService.Print:output_type -> printqueue.PrintResponse
	6, // 6: printqueue.PrintClientService.ClientPrint:output_type -> printqueue.ClientPrintResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_printqueue_proto_init() }
func file_printqueue_proto_init() {
	if File_printqueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_printqueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_printqueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_printqueue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPrintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_printqueue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPrintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_printqueue_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_printqueue_proto_goTypes,
		DependencyIndexes: file_printqueue_proto_depIdxs,
		EnumInfos:         file_printqueue_proto_enumTypes,
		MessageInfos:      file_printqueue_proto_msgTypes,
	}.Build()
	File_printqueue_proto = out.File
	file_printqueue_proto_rawDesc = nil
	file_printqueue_proto_goTypes = nil
	file_printqueue_proto_depIdxs = nil
}
